//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Table;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using UKHO.TidalPredictionService.Common.Helpers.EntityPropertyConverter;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
// CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="z_mta_interface", Namespace="urn:sap-com:document:sap:rfc:functions")]
public interface IZ_mta_interface {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:z_mta_interface:Z_MTA_INTERFACERequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Z_MTA_INTERFACEResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
   
    Z_MTA_INTERFACEResponse Z_MTA_INTERFACE([System.Xml.Serialization.XmlElementAttribute("Z_MTA_INTERFACE", Namespace="urn:sap-com:document:sap:rfc:functions")] Z_MTA_INTERFACE Z_MTA_INTERFACE1);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions",TypeName ="yq1")]

public partial class Z_MTA_INTERFACE
{    
    private ZMTA_SALES iM_ORDERField;
    
    public ZMTA_SALES IM_ORDER {
        get {
            return this.iM_ORDERField;
        }
        set {
            this.iM_ORDERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZMTA_SALES : TableEntity {
    
    private string uNIQUEIDField;
    
    private string tRANTYPField;
    
    private string nAMEField;
    
    private string aDDR1Field;
    
    private string aDDR2Field;
    
    private string cITYField;
    
    private string pOSTCODEField;
    
    private string sTATEField;
    
    private string cOUNTRYField;
    
    private string pHONEField;
    
    private string eMAILField;
    
    private string pONOField;
    
    private string pOURLField;
    
    private string gROSSAMOUNTField;
    
    private string fEEField;
    
    private string nETAMOUNTField;
    
    private string eRDATField;
    
    private string cURRENCYField;
    
    private ZMTA_PRODUCTS[] pRODUCTSField;


    /// <summary>
    /// To serialize and deserialize complex object for writing in azure storage.
    /// e.g. Basket
    /// </summary>
    public override IDictionary<string, EntityProperty> WriteEntity(OperationContext operationContext)
    {
        var results = base.WriteEntity(operationContext);
        EntityPropertyConvert.Serialize(this, results);
        return results;
    }

    public override void ReadEntity(IDictionary<string, EntityProperty> properties, OperationContext operationContext)
    {
        base.ReadEntity(properties, operationContext);
        EntityPropertyConvert.DeSerialize(this, properties);
    }


    /// <remarks/>

    public string UNIQUEID {
        get {
            return this.uNIQUEIDField;
        }
        set {
            this.uNIQUEIDField = value;
        }
    }
    
    /// <remarks/>
    
    public string TRANTYP {
        get {
            return this.tRANTYPField;
        }
        set {
            this.tRANTYPField = value;
        }
    }
    
    /// <remarks/>
    
    public string NAME {
        get {
            return this.nAMEField;
        }
        set {
            this.nAMEField = value;
        }
    }
    
    /// <remarks/>
    
    public string ADDR1 {
        get {
            return this.aDDR1Field;
        }
        set {
            this.aDDR1Field = value;
        }
    }
    
    /// <remarks/>
    
    public string ADDR2 {
        get {
            return this.aDDR2Field;
        }
        set {
            this.aDDR2Field = value;
        }
    }
    
    /// <remarks/>
    
    public string CITY {
        get {
            return this.cITYField;
        }
        set {
            this.cITYField = value;
        }
    }
    
    /// <remarks/>
    
    public string POSTCODE {
        get {
            return this.pOSTCODEField;
        }
        set {
            this.pOSTCODEField = value;
        }
    }
    
    /// <remarks/>
    
    public string STATE {
        get {
            return this.sTATEField;
        }
        set {
            this.sTATEField = value;
        }
    }
    
    /// <remarks/>
    
    public string COUNTRY {
        get {
            return this.cOUNTRYField;
        }
        set {
            this.cOUNTRYField = value;
        }
    }
    
    /// <remarks/>
    
    public string PHONE {
        get {
            return this.pHONEField;
        }
        set {
            this.pHONEField = value;
        }
    }
    
    /// <remarks/>
    
    public string EMAIL {
        get {
            return this.eMAILField;
        }
        set {
            this.eMAILField = value;
        }
    }
    
    /// <remarks/>
    
    public string PONO {
        get {
            return this.pONOField;
        }
        set {
            this.pONOField = value;
        }
    }
    
    /// <remarks/>
    
    public string POURL {
        get {
            return this.pOURLField;
        }
        set {
            this.pOURLField = value;
        }
    }
    
    /// <remarks/>
    
    public string GROSSAMOUNT {
        get {
            return this.gROSSAMOUNTField;
        }
        set {
            this.gROSSAMOUNTField = value;
        }
    }
    
    /// <remarks/>
    
    public string FEE {
        get {
            return this.fEEField;
        }
        set {
            this.fEEField = value;
        }
    }
    
    /// <remarks/>
    
    public string NETAMOUNT {
        get {
            return this.nETAMOUNTField;
        }
        set {
            this.nETAMOUNTField = value;
        }
    }
    
    /// <remarks/>
    
    public string ERDAT {
        get {
            return this.eRDATField;
        }
        set {
            this.eRDATField = value;
        }
    }
    
    /// <remarks/>
    
    public string CURRENCY {
        get {
            return this.cURRENCYField;
        }
        set {
            this.cURRENCYField = value;
        }
    }
    
    /// <remarks/>
    //[System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [EntityPropertyConverter(typeof(ZMTA_PRODUCTS[]))]
    public ZMTA_PRODUCTS[] PRODUCTS {
        get {
            return this.pRODUCTSField;
        }
        set {
            this.pRODUCTSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZMTA_PRODUCTS {
    
    private string pRODNAMEField;
    
    private string pRODDESCField;
    
    private string qTYField;
    
    private string pRICEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElement("PRODNAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public string PRODNAME {
        get {
            return this.pRODNAMEField;
        }
        set {
            this.pRODNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElement("PRODDESC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]

    public string PRODDESC {
        get {
            return this.pRODDESCField;
        }
        set {
            this.pRODDESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElement("QTY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]

    public string QTY {
        get {
            return this.qTYField;
        }
        set {
            this.qTYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElement("PRICE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]

    public string PRICE {
        get {
            return this.pRICEField;
        }
        set {
            this.pRICEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class Z_MTA_INTERFACEResponse {
    
    private string eX_MESSAGEField;
    
    private string eX_STATUSField;
    
    /// <remarks/>
    
    public string EX_MESSAGE {
        get {
            return this.eX_MESSAGEField;
        }
        set {
            this.eX_MESSAGEField = value;
        }
    }
    
    /// <remarks/>
    
    public string EX_STATUS {
        get {
            return this.eX_STATUSField;
        }
        set {
            this.eX_STATUSField = value;
        }
    }
}
